server:
  port: ${PORT:8081}


spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 497425525396-osmq8mgp2b062n8artl2f08g7a236rq5.apps.googleusercontent.com
            clientSecret: CPs2ejjynU15lJJAO3SZLyUM